{{- if .Values.configMap.app -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.app }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{ if .Values.env }}
{{ .Values.env | toYaml | indent 3 }}
{{ end }}
{{ end }}